// Code generated by protoc-gen-go. DO NOT EDIT.
// source: secrets.proto

/*
Package secrets is a generated protocol buffer package.

It is generated from these files:
	secrets.proto

It has these top-level messages:
	Secret
	Secrets
*/
package secrets

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Secret struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Secret) Reset()                    { *m = Secret{} }
func (m *Secret) String() string            { return proto.CompactTextString(m) }
func (*Secret) ProtoMessage()               {}
func (*Secret) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Secret) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Secret) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Secrets struct {
	Secrets []*Secret `protobuf:"bytes,1,rep,name=secrets" json:"secrets,omitempty"`
}

func (m *Secrets) Reset()                    { *m = Secrets{} }
func (m *Secrets) String() string            { return proto.CompactTextString(m) }
func (*Secrets) ProtoMessage()               {}
func (*Secrets) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Secrets) GetSecrets() []*Secret {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func init() {
	proto.RegisterType((*Secret)(nil), "secrets.Secret")
	proto.RegisterType((*Secrets)(nil), "secrets.Secrets")
}

func init() { proto.RegisterFile("secrets.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x4d, 0x2e,
	0x4a, 0x2d, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x8c, 0xb8,
	0xd8, 0x82, 0xc1, 0x4c, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0xce, 0x20, 0x30, 0x5b, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82, 0x09,
	0x2c, 0x08, 0xe1, 0x28, 0x99, 0x70, 0xb1, 0x43, 0xf4, 0x14, 0x0b, 0x69, 0x72, 0xc1, 0x4c, 0x92,
	0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0xe2, 0xd7, 0x83, 0x59, 0x04, 0x51, 0x12, 0x04, 0x93, 0x4f,
	0x62, 0x03, 0xdb, 0x6c, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xdf, 0x47, 0x11, 0x8a, 0x00,
	0x00, 0x00,
}
